# Generated by Django 4.1.4 on 2022-12-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litlelemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='menu_item',
            new_name='menu_item_id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='category',
            new_name='user',
        ),
    ]
