# Generated by Django 4.1.4 on 2022-12-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=255)),
                ('autor', models.CharField(db_index=True, max_length=255)),
                ('descricao', models.CharField(max_length=300)),
                ('quantidade', models.SmallIntegerField(db_index=True)),
            ],
        ),
    ]
