# Generated by Django 4.1.4 on 2022-12-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='livro',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='livro',
            name='quantidade',
            field=models.SmallIntegerField(),
        ),
    ]
