# Generated by Django 4.1.4 on 2022-12-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaAPI', '0002_livro_price_alter_livro_autor_alter_livro_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
        ),
    ]
