# Generated by Django 4.1.4 on 2022-12-13 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaAPI', '0003_alter_livro_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='livro',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bibliotecaAPI.category'),
        ),
    ]
