# Generated by Django 4.1.4 on 2022-12-15 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaAPI', '0007_alter_livro_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bibliotecaAPI.category'),
        ),
    ]
